# Generated by Django 6.1.1 on 2026-09-07 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'fuente',
                'verbose_name_plural': 'fuentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('numerico', 'Numérico'), ('cualitativo', 'Cualitativo')], max_length=20)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='indicadores.categoria')),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores', to='indicadores.fuente')),
            ],
            options={
                'verbose_name': 'indicador',
                'verbose_name_plural': 'indicadores',
                'ordering': ['categoria', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='EventoTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=300)),
                ('sentimiento', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('neutral', 'Neutral')], max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_timeline', to='indicadores.categoria')),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_timeline', to='indicadores.fuente')),
            ],
            options={
                'verbose_name': 'evento de línea de tiempo',
                'verbose_name_plural': 'eventos de línea de tiempo',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='idx_eventos_fecha')],
            },
        ),
        migrations.CreateModel(
            name='IndicadorValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('granularidad', models.CharField(choices=[('dia', 'Día'), ('semana', 'Semana'), ('mes', 'Mes'), ('anio', 'Año')], max_length=10)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('valor_texto', models.CharField(blank=True, max_length=200)),
                ('delta_texto', models.CharField(blank=True, max_length=100)),
                ('trend', models.CharField(blank=True, choices=[('up', 'Sube'), ('down', 'Baja'), ('flat', 'Sin cambios')], max_length=10)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='indicadores.indicador')),
            ],
            options={
                'verbose_name': 'valor de indicador',
                'verbose_name_plural': 'valores de indicadores',
                'ordering': ['indicador', 'granularidad', 'fecha'],
                'indexes': [models.Index(fields=['indicador', 'granularidad', '-fecha'], name='idx_valores_ind_gran_fecha')],
                'constraints': [models.UniqueConstraint(fields=('indicador', 'fecha', 'granularidad'), name='uq_indicador_fecha_gran')],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=300)),
                ('bajada', models.TextField(blank=True)),
                ('cuerpo', models.TextField(blank=True)),
                ('publicado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='indicadores.categoria')),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='indicadores.fuente')),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['categoria', '-fecha'], name='idx_noticias_cat_fecha')],
            },
        ),
    ]
