# Generated by Django 6.1.1 on 2026-09-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gobierno',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('presidente', models.CharField(max_length=150)),
                ('partido', models.CharField(blank=True, max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'gobierno',
                'verbose_name_plural': 'gobiernos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=500)),
                ('tipo', models.CharField(choices=[('diario', 'Diario / digital de noticias'), ('agencia', 'Agencia de noticias'), ('tv', 'Televisión'), ('radio', 'Radio'), ('revista', 'Revista'), ('factchecking', 'Verificación de datos')], max_length=20)),
                ('orientacion', models.CharField(choices=[('izquierda', 'Izquierda'), ('centro_izquierda', 'Centro-izquierda'), ('centro', 'Centro'), ('centro_derecha', 'Centro-derecha'), ('derecha', 'Derecha')], max_length=20)),
                ('descripcion', models.TextField(help_text='Breve justificación de la caracterización — de dónde viene, no solo la etiqueta.')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'medio de comunicación',
                'verbose_name_plural': 'medios de comunicación',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
