# Generated by Django 6.1.1 on 2026-09-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0002_gobierno_medio'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='actualizacion_automatica',
            field=models.BooleanField(default=False, help_text='True si el comando fetch_datos_reales trae este indicador de una fuente externa real (BCRA, datos.gob.ar, dolarapi.com). False si el valor es ilustrativo o se carga a mano desde el admin. No es solo informativo: antes esta distinción vivía únicamente como una lista de IDs hardcodeada dentro de fetch_datos_reales.py — este campo la hace explícita y consultable (acá, en el admin, y en la API) en vez de tener que leer el código para saber qué indicador es "de verdad".'),
        ),
    ]
