# Generated by Django 6.1.1 on 2026-09-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0003_indicador_actualizacion_automatica'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulsoIndexSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('mejorando', models.PositiveIntegerField()),
                ('empeorando', models.PositiveIntegerField()),
                ('sin_cambio', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'foto del índice general',
                'verbose_name_plural': 'fotos del índice general',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='indicador',
            name='polaridad',
            field=models.CharField(choices=[('positivo', 'Subir es mejorar'), ('negativo', 'Subir es empeorar'), ('neutral', 'Sin dirección de consenso — excluido del índice general')], default='neutral', help_text='Si subir este indicador es una mejora o un empeoramiento del país — la base del índice general (ver services/pulso_index.py). "neutral" para todo lo ideológicamente contestado (dólar, gasto militar, aprobación de gobierno, etc.): esos quedan afuera del índice a propósito, no por descuido. Se fija en seed_pulso_austral.py (POLARIDADES), igual que actualizacion_automatica.', max_length=10),
        ),
    ]
