# Generated by Django 6.1.1 on 2026-09-07 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0004_pulsoindexsnapshot_indicador_polaridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='fuente',
        ),
        migrations.AddField(
            model_name='indicador',
            name='metodologia',
            field=models.TextField(blank=True, help_text='Cómo se mide/calcula este indicador — para la sección de glosario del sitio.'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='medio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='indicadores.medio'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='url',
            field=models.URLField(blank=True, help_text='Link a la nota original. Puede quedar roto con el tiempo — titulo/bajada no dependen de esto.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='bajada',
            field=models.TextField(blank=True, help_text='Resumen breve y persistente — no depende de que `url` siga viva.'),
        ),
    ]
